### ISSUE TITLE
Screencapturing tool

### ISSUE THREAD

**Issue by hjudt** [LionyxML/ros#6]
On many linux distributions, imagemagick is installed per default, providing the `import` command, which can take screenshots like scrot (single click for the window, click and drag for an area, or call it with parameter -window root for the whole screen). Maybe consider setting this as default, thus not requiring the user to install an additional tool. While it has a plethora of options, it only needs the filename as parameter.

**Comment by LionyxML** [comment]
Thanks for your feedback!

I'm gonna get some Linux install shortly in order to make all sort of adjustments before imagemagick is supported by default.

In the meantime I just added both the screenshot and switch variables as customizable so you can  `M-x customize` `org-ros` `RET` and customize it to your needs :)

![image](https://user-images.githubusercontent.com/16169950/157135483-b6580e5b-f63e-4fc7-b4cb-35ff082d71c5.png)
